//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTracker.AdoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sessions
    {
        public int IdSession { get; set; }
        public int CategoryId { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.TimeSpan TimeStart { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
